name: build

on:
  push:
    branches:
      - main
      - 'renovate/**'

  pull_request:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        distro: [focal, bionic]
        arch: [x86_64]

    env:
      DISTRO: ${{ matrix.distro }} # build target, name required by binary-builder
      ARCH: ${{ matrix.arch }} # build target, name required by binary-builder

    steps:
      - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # renovate: tag=v2.3.5

      - name: binary-builder
        uses: renovatebot/internal-tools@93fee20c90552ee7793f5873e627b4299186ceee # renovate: tag=v1.9.1
        with:
          command: binary-builder
          dry-run: ${{github.ref != 'refs/heads/main'}}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@27121b0bdffd731efa15d66772be8dc71245d074 # renovate: tag=v2.2.4
        with:
          name: ${{ env.DISTRO }}
          path: .cache/*.tar.xz
